-- File generated by the BNF Converter (bnfc 2.9.4.1).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Dummy.

module Dummy.Abs where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Prog = Dummy_Prog [ClassDec] [InstDec] [Expr]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ClassOpDec = ClassOp_Dec LIdent SType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ClassOpImp = ClassOp_Imp LIdent Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ClassDec = Class_Dec UIdent LIdent [ClassOpDec]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data InstDec = Inst_Dec UIdent [ClassOpImp]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Expr
    = Ass_Expr LIdent Expr
    | Abst_Expr LIdent Expr
    | Var_Expr LIdent
    | App_Expr Expr Expr
    | List_Expr List
    | LCase_Expr Expr List Expr List Expr
    | True_Expr True
    | False_Expr False
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data List = Nil | Cons LIdent List
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TyC = TypeConstraint UIdent SType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data OvType = OverLoadedType [TyC] SType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SType
    = TVar_SType LIdent
    | TCons_SType UIdent LIdent
    | Bool_SType
    | Arrow_SType SType SType
    | List_SType SType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data DType = DType_OvType OvType | DType_SType SType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype UIdent = UIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype LIdent = LIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype True = True String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype False = False String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

